language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq -d update
  - wget "http://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.gz"
  - tar zxf boost_1_55_0.tar.gz

install:
  - sudo apt-get -qq install libboost1.55-all-dev cmake g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script:
  - bin/configlet-linux-amd64 .
  - (cd boost_1_55_0; ./bootstrap.sh; ./b2 --with-date_time --with-iostreams --with-regex --with-system link=static)
  - cmake -G "Unix Makefiles"
  - make
